// <auto-generated />
namespace EFMysql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class change940820 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change940820));
        
        string IMigrationMetadata.Id
        {
            get { return "201511110901101_change940820"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
